---
#PUT here your main variable
timezone: Europe/Paris
project_name: <%= appName %>
port: 80
apt_install:
  - git

# Needed for the apt role to work with ansible 2.0
apt_install_repositories: []
apt_remove_repositories: []
apt_remove: []
nodejs_version: 6
